# Generated by Django 3.0.5 on 2020-05-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_msg_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
